set(_CATKIN_CURRENT_PACKAGE "ap0")
set(ap0_VERSION "0.0.0")
set(ap0_MAINTAINER "despina <despina@todo.todo>")
set(ap0_PACKAGE_FORMAT "2")
set(ap0_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(ap0_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(ap0_BUILDTOOL_DEPENDS "catkin")
set(ap0_BUILDTOOL_EXPORT_DEPENDS )
set(ap0_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(ap0_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(ap0_TEST_DEPENDS )
set(ap0_DOC_DEPENDS )
set(ap0_URL_WEBSITE "")
set(ap0_URL_BUGTRACKER "")
set(ap0_URL_REPOSITORY "")
set(ap0_DEPRECATED "")